name: On Pull Request To Main

on:
  pull_request:
    branches:
      - main

jobs:
  job1:
    name: Analyze, Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Angular
      run: npm i -g @angular/cli

    - name: Install dependencies
      run: npm i

    - name: Build
      run: ng b ngx-corebox