name: On Push To Main

on:
  pull_request:
    branches:
      - main

jobs:
  job1:
    name: "On Push To Main"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true

      - name: 'change version'
        uses: reedyuk/npm-version@1.1.1
        with:
          version: '${{ steps.gitversion.outputs.new_tag }}'
          package: 'subproject-directory/'
          git-tag-version: 'true'

      - run: npm run-script build
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}