name: On Push To Main

on:
  pull_request:
    branches:
      - main

jobs:
  job1:
    name: "On Push To Main"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Process version of the tag
        id: version
        uses: ncipollo/semantic-version-action@v1
      
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps.version.outputs) }}
        run: echo "$STEPS_CONTEXT"
      
      - name: Dump previous tag
        env:
          PREVIOUS_TAG: ${{ steps.version.outputs.previous_tag }}
        run: echo "$PREVIOUS_TAG"

      - name: 'change version'
        uses: reedyuk/npm-version@1.1.1
        with:
          version: '${{ steps.gitversion.outputs.new_tag }}'
          package: 'subproject-directory/'
          git-tag-version: 'true'

      - run: npm run-script build
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}