name: On Push To Main

on:
  pull_request:
    branches:
      - main

jobs:
  job1:
  
    name: "On Push To Main"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: dotnet Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - run: dotnet new tool-manifest
      - run: dotnet tool install --local GitVersion.Tool --version 5.11.1
      - run: dotnet gitversion /output buildserver

      - name: 'change version'
        uses: reedyuk/npm-version@1.1.1
        with:
          version: '${{ steps.gitversion.outputs.new_tag }}'
          package: 'subproject-directory/'
          git-tag-version: 'true'

      - run: npm run-script build
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}