on:
  pull_request:
    branches:
      - main

jobs:
  job1:
    name: "On Push To Main"
    runs-on: ubuntu-test

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
        env:
        
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}