name: On Push To Main

on:
  pull_request:
    branches:
      - main

jobs:
  job1:
    name: "On Push To Main"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: 'kenkko-group'

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true

      - run: |
          git config --global user.email "infra@kenkko.group"
          git config --global user.name "Tecnologia Kenkko group"
          
      - run: npm version ${{ steps.gitversion.outputs.semVer }}
      - run: npm install -g @angular/cli
      - run: npm install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: ng build ngx-corebox --configuration production
      - run: npm ci
      - run: |
        echo "//https://registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}">.npmrc
        npm publish