name: On Push To Main

on:
  push:
    branches:
      - main

jobs:
  job1:
    name: Update Version and Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: GitVersion Setup
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: GitVersion Execute
      uses: gittools/actions/gitversion/execute@v0.9.7
      id: gitversion
      with:
        useConfigFile: true

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Angular
      run: npm i -g @angular/cli

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: ng b ngx-corebox

    - name: Move to binary folder
      run: cd dist/ngx-corebox

    - run: |
          git config --global user.email "${{ secrets.INFRA_EMAIL }}"
          git config --global user.name "Kenkko group"

    - name: Set Version
      run: npm version ${{ steps.gitversion.outputs.semVer }}

    - name: Publish
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}